# Generated by Django 2.0.3 on 2018-12-21 11:33

import apps.privado.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_category', models.IntegerField(choices=[(0, 'SINIC-SAT'), (1, 'Anexo RRHH '), (2, 'ModusOperandis '), (3, 'Vivienda '), (4, 'Área Finanzas ')], validators=[apps.privado.validators.tipo_validacion])),
                ('file_logo', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('file_name', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('file_description', models.CharField(max_length=250)),
                ('file_upload', models.FileField(upload_to='documentos/')),
            ],
            options={
                'db_table': 'publico_documentos',
            },
        ),
    ]
