# Generated by Django 2.0.3 on 2018-04-11 14:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
