# Generated by Django 2.0.5 on 2019-04-17 14:19

import apps.privado.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Articulo'), (2, 'Video')], validators=[apps.privado.validators.tipo_validacion])),
                ('jurisdiccion', models.IntegerField(choices=[(0, 'Provincial'), (1, 'Jefatura de Policia - Rawson'), (2, 'Unidad Regional Comodoro Rivadavia'), (3, 'Unidad Regional Esquel'), (4, 'Unidad Regional Puerto Madryn'), (5, 'Unidad Regional Trelew')], validators=[apps.privado.validators.tipo_validacion])),
                ('categoria', models.IntegerField(choices=[(0, 'Informativo'), (1, 'Institucional'), (2, 'Comunidad'), (3, 'Otro')], validators=[apps.privado.validators.tipo_validacion])),
                ('titulo', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('contenido', models.TextField(validators=[apps.privado.validators.texto_validacion])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones', validators=[apps.privado.validators.imagen_validacion])),
                ('url', models.URLField()),
                ('fuente', models.CharField(max_length=200, validators=[apps.privado.validators.texto_validacion])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_archivado', models.DateTimeField(blank=True, null=True)),
                ('intro', models.CharField(blank=True, max_length=350, null=True)),
                ('is_publicado', models.BooleanField(default=False)),
                ('is_archivado', models.BooleanField(default=False)),
                ('is_para_portada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete='CASCADE', related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
