# Generated by Django 2.0.3 on 2018-07-18 16:47

import apps.privado.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0002_auto_20180717_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='jurisdiccion',
            field=models.IntegerField(choices=[(0, 'Provincial'), (1, 'Jefatura de Policia - Rawson'), (2, 'Unidad Regional Comodoro Rivadavia'), (3, 'Unidad Regional Esquel'), (4, 'Unidad Regional Puerto Madryn'), (5, 'Unidad Regional Trelew')], validators=[apps.privado.validators.tipo_validacion]),
        ),
    ]
