# Generated by Django 2.0.3 on 2018-04-18 14:18

import apps.privado.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'articulo'), (2, 'video')], default=1, validators=[apps.privado.validators.tipo_validacion])),
                ('titulo', models.CharField(max_length=50, validators=[apps.privado.validators.texto_validacion])),
                ('contenido', models.TextField(validators=[apps.privado.validators.texto_validacion])),
                ('url', models.URLField()),
                ('fuente', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=django.contrib.auth.models.User, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
