# Generated by Django 2.0.3 on 2018-06-08 20:58

import apps.privado.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerarquia', models.IntegerField(choices=[(1, 'Crio. General'), (2, 'Crio. Mayor'), (3, 'Crio. Inspector'), (4, 'Comisario'), (5, 'SubCrio.'), (6, 'Of. Principal'), (7, 'Of. Inspector.'), (8, 'Of. SubInsp.'), (9, 'Retirado'), (10, 'Retirado en servicio')], default=1, validators=[apps.privado.validators.tipo_validacion])),
                ('cargo', models.IntegerField(choices=[(1, 'Jefe de Policia'), (2, 'SubJefe de Policia'), (3, 'Secretario General'), (4, 'Director'), (5, 'Jefe de Area'), (6, 'SubJefe de Area'), (7, 'Jefe'), (8, 'SubJefe')], default=1, validators=[apps.privado.validators.tipo_validacion])),
                ('dependencia', models.IntegerField(choices=[(1, 'Jefatura de Policia'), (2, 'Secretaria General'), (3, 'Direccion Seguridad'), (4, 'Direccion Recursos Humanos'), (5, 'Direccion Recursos Materiales'), (6, 'Direccion Policia Judicial')], default=1, validators=[apps.privado.validators.tipo_validacion])),
                ('nombre', models.CharField(max_length=20, validators=[apps.privado.validators.texto_validacion])),
                ('segundo_nombre', models.CharField(max_length=20, validators=[apps.privado.validators.texto_validacion])),
                ('apellido', models.CharField(max_length=20, validators=[apps.privado.validators.texto_validacion])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='autoridades', validators=[apps.privado.validators.imagen_validacion])),
                ('direccion_laboral', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('telefono_laboral', models.CharField(blank=True, max_length=35, validators=[apps.privado.validators.telefono_validacion])),
                ('telefono', models.CharField(blank=True, max_length=35, validators=[apps.privado.validators.telefono_validacion])),
                ('email', models.EmailField(max_length=254)),
                ('trayectoria', models.TextField(validators=[apps.privado.validators.texto_validacion])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_publicado', models.BooleanField(default=False)),
                ('is_archivado', models.BooleanField(default=False)),
                ('is_para_portada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(default=django.contrib.auth.models.User, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Articulo'), (2, 'Video')], validators=[apps.privado.validators.tipo_validacion])),
                ('jurisdiccion', models.IntegerField(choices=[(0, 'Provincial'), (1, 'Jefatura de Policia'), (2, 'Unidad Regional Comodoro Rivadavia'), (3, 'Unidad Regional Esquel'), (4, 'Unidad Regional Puerto Madryn'), (5, 'Unidad Regional Trelew')], validators=[apps.privado.validators.tipo_validacion])),
                ('categoria', models.IntegerField(choices=[(0, 'Informativo'), (1, 'Institucional'), (2, 'Comunidad'), (3, 'Otro')], validators=[apps.privado.validators.tipo_validacion])),
                ('titulo', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('contenido', models.TextField(validators=[apps.privado.validators.texto_validacion])),
                ('url', models.URLField()),
                ('fuente', models.CharField(max_length=200, validators=[apps.privado.validators.texto_validacion])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_archivado', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones', validators=[apps.privado.validators.imagen_validacion])),
                ('intro', models.CharField(blank=True, max_length=350, null=True)),
                ('is_publicado', models.BooleanField(default=False)),
                ('is_archivado', models.BooleanField(default=False)),
                ('is_para_portada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(default=django.contrib.auth.models.User, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
