# Generated by Django 2.0.3 on 2018-07-17 15:13

import apps.privado.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(validators=[apps.privado.validators.texto_validacion]),
        ),
    ]
