# Generated by Django 2.0.3 on 2018-05-29 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El telefono debe tener formato: '+999999999'. Hasta 15 digitos es permitido.", regex='^(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}$/D')]),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='telefono_laboral',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El telefono debe tener formato: '+999999999'. Hasta 15 digitos es permitido.", regex='^(?:(?:00)?549?)?0?(?:11|[2368]\\d)(?:(?=\\d{0,2}15)\\d{2})??\\d{8}$/D')]),
        ),
    ]
