# Generated by Django 2.0.5 on 2019-04-17 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(on_delete='CASCADE', related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
