# Generated by Django 2.0.3 on 2018-06-29 16:05

import apps.privado.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiccion', models.IntegerField(choices=[(0, 'Provincial'), (1, 'Jefatura de Policia'), (2, 'Unidad Regional Comodoro Rivadavia'), (3, 'Unidad Regional Esquel'), (4, 'Unidad Regional Puerto Madryn'), (5, 'Unidad Regional Trelew')], validators=[apps.privado.validators.tipo_validacion])),
                ('funcion', models.IntegerField(choices=[(0, 'Seguridad'), (1, 'Escuela')], validators=[apps.privado.validators.tipo_validacion])),
                ('nombre', models.CharField(max_length=50, validators=[apps.privado.validators.texto_validacion])),
                ('direccion', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('ciudad', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('telefono', models.CharField(blank=True, max_length=35, validators=[apps.privado.validators.telefono_validacion])),
                ('email', models.EmailField(max_length=254)),
                ('jefe', models.CharField(max_length=50, validators=[apps.privado.validators.texto_validacion])),
                ('subjefe', models.CharField(max_length=50, validators=[apps.privado.validators.texto_validacion])),
                ('ubicacion', models.CharField(max_length=150, validators=[apps.privado.validators.ubicacion_validacion])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='dependencias', validators=[apps.privado.validators.imagen_validacion])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_publicado', models.BooleanField(default=False)),
                ('is_archivado', models.BooleanField(default=False)),
                ('is_para_portada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(default=django.contrib.auth.models.User, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
