# Generated by Django 2.0.3 on 2018-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0002_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='fecha_archivado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='fecha_archivado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
