# Generated by Django 2.0.2 on 2018-04-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0002_auto_20180426_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones'),
        ),
    ]
