# Generated by Django 2.0.5 on 2020-07-13 16:47

import apps.privado.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privado', '0002_auto_20190417_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Resistencia'), (2, 'Elongacion')], validators=[apps.privado.validators.tipo_validacion])),
                ('zona', models.IntegerField(choices=[(0, 'Tren Superior'), (1, 'Zona Superior'), (2, 'Tren Inferior')], validators=[apps.privado.validators.tipo_validacion])),
                ('objetivo', models.TextField(validators=[apps.privado.validators.texto_validacion])),
                ('nombre', models.CharField(max_length=100, validators=[apps.privado.validators.texto_validacion])),
                ('intensidad', models.TextField(validators=[apps.privado.validators.texto_validacion])),
                ('detalle', models.TextField(validators=[apps.privado.validators.texto_validacion])),
                ('url', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios', validators=[apps.privado.validators.imagen_validacion])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_archivado', models.DateTimeField(blank=True, null=True)),
                ('is_publicado', models.BooleanField(default=False)),
                ('is_archivado', models.BooleanField(default=False)),
                ('is_para_portada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
