# Generated by Django 2.0.3 on 2018-05-02 12:07

import apps.privado.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0003_auto_20180426_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fuente',
            field=models.CharField(max_length=150, validators=[apps.privado.validators.texto_validacion]),
        ),
    ]
