# Generated by Django 2.0.3 on 2018-07-12 14:08

import apps.privado.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0003_auto_20180704_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones', validators=[apps.privado.validators.imagen_validacion])),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='privado.Album')),
            ],
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='album',
            name='publicacion',
            field=models.OneToOneField(null=True, on_delete='CASCADE', to='privado.Publicacion'),
        ),
    ]
