# Generated by Django 2.0.3 on 2018-05-30 13:45

import apps.privado.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0004_auto_20180530_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Jefe de Policia'), (2, 'SubJefe de Policia'), (3, 'Secretario General'), (4, 'Director'), (5, 'Jefe de Area'), (6, 'SubJefe de Area'), (7, 'Jefe'), (8, 'SubJefe')], default=1, validators=[apps.privado.validators.tipo_validacion]),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='jerarquia',
            field=models.IntegerField(choices=[(1, 'Crio. General'), (2, 'Crio. Mayor'), (3, 'Crio. Inspector'), (4, 'Comisario'), (5, 'SubCrio.'), (6, 'Of. Principal'), (7, 'Of. Inspector.'), (8, 'Of. SubInsp.'), (9, 'Retirado'), (10, 'Retirado en servicio')], default=1, validators=[apps.privado.validators.tipo_validacion]),
        ),
    ]
