# Generated by Django 2.0.3 on 2018-07-12 14:51

import apps.privado.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0004_auto_20180712_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones', validators=[apps.privado.validators.imagen_validacion])),
                ('publicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='privado.Publicacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='albumfoto',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AlbumFoto',
        ),
    ]
