# Generated by Django 2.0.3 on 2018-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0004_auto_20180502_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
