# Generated by Django 2.0.3 on 2018-05-30 14:37

import apps.privado.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0005_auto_20180530_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Articulo'), (2, 'Video')], default=1, validators=[apps.privado.validators.tipo_validacion]),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='jurisdiccion',
            field=models.IntegerField(choices=[(1, 'Articulo'), (2, 'Video')], default=1, validators=[apps.privado.validators.tipo_validacion]),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Articulo'), (2, 'Video')], default=1, validators=[apps.privado.validators.tipo_validacion]),
        ),
    ]
