# Generated by Django 2.0.3 on 2018-05-03 12:56

import apps.privado.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0007_auto_20180503_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fuente',
            field=models.CharField(max_length=200, validators=[apps.privado.validators.texto_validacion]),
        ),
    ]
