# Generated by Django 2.0.3 on 2018-05-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0008_auto_20180503_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='intro',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
